#! /usr/bin/bash
set -x

cdf=concat_demuxer_file
output=tmp_output

source="$1"
if [ -z "$source" ]; then
    echo need source
    exit 1
fi
shift 1

if [ -z "$1" ]; then
    echo need time
    exit 1
fi

if [ "${source##*.}" == 'mkv' ]; then
    ext="mkv"
elif [ "${source##*.}" == 'wmv' ]; then
    ext="mkv"
else
    ext="mp4"
fi

if [[ -f $cdf ]];
then
    trash $cdf
elif [[ -e $cdf ]];
then
    echo "conflicted \'concat_demuxer_file\' filename!"
    exit 1
fi

while [ -n "$1" ]; do
    echo "file '$source'" >> $cdf
    echo "inpoint $1" >> $cdf
    shift 1
    if [ -n "$1" ]; then
        echo "outpoint $1" >> $cdf
        shift 1
    fi
done

ffmpeg -f concat -i $cdf -c copy "${output}.${ext}"
trash "$source"
trash "$cdf"
mv "${output}.${ext}" "${source%.*}.${ext}"
